version: '2'
services:
    voilavoix2-app:
        image: voilavoix2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://voilavoix2-mysql:3306/voilavoix2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    voilavoix2-mysql:
        extends:
            file: mysql.yml
            service: voilavoix2-mysql
